In [1]:
input = [2,3,1,3,4,4,1,5,2,3,1,1,4,5,5,3,5,5,4,1,2,1,1,1,1,1,1,4,1,1,1,4,1,3,1,4,1,1,4,1,3,4,5,1,1,5,3,4,3,4,1,5,1,3,1,1,1,3,5,3,2,3,1,5,2,2,1,1,4,1,1,2,2,2,2,3,2,1,2,5,4,1,1,1,5,5,3,1,3,2,2,2,5,1,5,2,4,1,1,3,3,5,2,3,1,2,1,5,1,4,3,5,2,1,5,3,4,4,5,3,1,2,4,3,4,1,3,1,1,2,5,4,3,5,3,2,1,4,1,4,4,2,3,1,1,2,1,1,3,3,3,1,1,2,2,1,1,1,5,1,5,1,4,5,1,5,2,4,3,1,1,3,2,2,1,4,3,1,1,1,3,3,3,4,5,2,3,3,1,3,1,4,1,1,1,2,5,1,4,1,2,4,5,4,1,5,1,5,5,1,5,5,2,5,5,1,4,5,1,1,3,2,5,5,5,4,3,2,5,4,1,1,2,4,4,1,1,1,3,2,1,1,2,1,2,2,3,4,5,4,1,4,5,1,1,5,5,1,4,1,4,4,1,5,3,1,4,3,5,3,1,3,1,4,2,4,5,1,4,1,2,4,1,2,5,1,1,5,1,1,3,1,1,2,3,4,2,4,3,1]

<h4>Part 1</h4>

In [2]:
# "bruteforce" method with class

all_fish = list()

class fish:
    
    def __init__(self):
    
        self.age = 0

    @property
    def age_a_day(self):
        
        if self.age == 0:
            
            self.age = 6

            # if age is now six - spawn
            f = fish()
            f.age = 8
            all_fish.append(f)
            
        else:
            
            self.age = self.age -1

# define the fish classes
for age in input:
    
    f = fish()
    f.age = age
    all_fish.append(f)    

In [3]:
# age the fish
for d in range(81):
    
    if d in [10,20,30,40,50,60,70,80]:
        
        print(f'Day no. {d} Fish count: {len(all_fish)}')
    
    for i in range(len(all_fish)):
        
        all_fish[i].age_a_day

Day no. 10 Fish count: 752
Day no. 20 Fish count: 2009
Day no. 30 Fish count: 4609
Day no. 40 Fish count: 10511
Day no. 50 Fish count: 26405
Day no. 60 Fish count: 62227
Day no. 70 Fish count: 147974
Day no. 80 Fish count: 358214


<h4>Part 2</h4>

In [63]:
# try do it with numpy and write out data to file

import numpy as np
from tqdm.notebook import tqdm, trange

input = [2,3,1,3,4,4,1,5,2,3,1,1,4,5,5,3,5,5,4,1,2,1,1,1,1,1,1,4,1,1,1,4,1,3,1,4,1,1,4,1,3,4,5,1,1,5,3,4,3,4,1,5,1,3,1,1,1,3,5,3,2,3,1,5,2,2,1,1,4,1,1,2,2,2,2,3,2,1,2,5,4,1,1,1,5,5,3,1,3,2,2,2,5,1,5,2,4,1,1,3,3,5,2,3,1,2,1,5,1,4,3,5,2,1,5,3,4,4,5,3,1,2,4,3,4,1,3,1,1,2,5,4,3,5,3,2,1,4,1,4,4,2,3,1,1,2,1,1,3,3,3,1,1,2,2,1,1,1,5,1,5,1,4,5,1,5,2,4,3,1,1,3,2,2,1,4,3,1,1,1,3,3,3,4,5,2,3,3,1,3,1,4,1,1,1,2,5,1,4,1,2,4,5,4,1,5,1,5,5,1,5,5,2,5,5,1,4,5,1,1,3,2,5,5,5,4,3,2,5,4,1,1,2,4,4,1,1,1,3,2,1,1,2,1,2,2,3,4,5,4,1,4,5,1,1,5,5,1,4,1,4,4,1,5,3,1,4,3,5,3,1,3,1,4,2,4,5,1,4,1,2,4,1,2,5,1,1,5,1,1,3,1,1,2,3,4,2,4,3,1]
fish = np.array(input)

# age the fish
for d in tqdm(range(1, 256+1)):
    
    # deal with zeros
    fish = np.where(fish ==0, 7, fish)
    fish = np.where(fish ==10, 7, fish)
    
    # age a day
    fish = fish-1
    
    # check for sixes       
    fish = np.append(fish, np.zeros(len(np.where(fish == 6)[0]))+18)
    
    if d in [256,200,150,100,50]:
        
        print(f'Day no. {d} Fish count: {len(fish)}')
        
    f = open('data_pt2.csv', 'a')
    f.write(f'{d},{len(fish)}\n')
    f.close()
    
print(f'Final Fish count: {len(fish)}')

  0%|          | 0/80 [00:00<?, ?it/s]

Day no. 50 Fish count: 26405
Final Fish count: 358214


In [2]:
# chop it into blocks

import numpy as np
from tqdm.notebook import tqdm, trange

final_fish_count = 0

input = [2,3,1,3,4,4,1,5,2,3,1,1,4,5,5,3,5,5,4,1,2,1,1,1,1,1,1,4,1,1,1,4,1,3,1,4,1,1,4,1,3,4,5,1,1,5,3,4,3,4,1,5,1,3,1,1,1,3,5,3,2,3,1,5,2,2,1,1,4,1,1,2,2,2,2,3,2,1,2,5,4,1,1,1,5,5,3,1,3,2,2,2,5,1,5,2,4,1,1,3,3,5,2,3,1,2,1,5,1,4,3,5,2,1,5,3,4,4,5,3,1,2,4,3,4,1,3,1,1,2,5,4,3,5,3,2,1,4,1,4,4,2,3,1,1,2,1,1,3,3,3,1,1,2,2,1,1,1,5,1,5,1,4,5,1,5,2,4,3,1,1,3,2,2,1,4,3,1,1,1,3,3,3,4,5,2,3,3,1,3,1,4,1,1,1,2,5,1,4,1,2,4,5,4,1,5,1,5,5,1,5,5,2,5,5,1,4,5,1,1,3,2,5,5,5,4,3,2,5,4,1,1,2,4,4,1,1,1,3,2,1,1,2,1,2,2,3,4,5,4,1,4,5,1,1,5,5,1,4,1,4,4,1,5,3,1,4,3,5,3,1,3,1,4,2,4,5,1,4,1,2,4,1,2,5,1,1,5,1,1,3,1,1,2,3,4,2,4,3,1]

def block(l, n):
    
    for i in range(0, len(l), n): 
        yield l[i:i + n]

block_input = block(input, 1)

for b in block_input:

    fish = np.array(b)

    # age the fish
    for d in tqdm(range(1, 256+1)):

        # deal with zeros
        fish = np.where(fish ==0, 7, fish)
        fish = np.where(fish ==10, 7, fish)

        # age a day
        fish = fish-1

        # check for sixes       
        fish = np.append(fish, np.zeros(len(np.where(fish == 6)[0]))+18)

    final_fish_count = final_fish_count + len(fish)
    print(f'Block Fish count: {len(fish)}')

print(f'Final Fish count: {final_fish_count}')

  0%|          | 0/256 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [8]:
input = [[2,10],[3,5],[1,3]]
fish = np.array(input, np.int32)

minus = [[1,0],[1,0],[1,0]]

In [9]:
fish-minus

array([[ 1, 10],
       [ 2,  5],
       [ 0,  3]])

In [57]:
input = [2,3,1,3,4,4,1,5,2,3,1,1,4,5,5,3,5,5,4,1,2,1,1,1]
unique, counts = np.unique(input, return_counts=True)

fish = np.array(list(zip(unique, counts)), np.int32)

# append zeros for 8-6
new_fish =  np.array([[6,0],[7,0],[8,0]], np.int32)

fish = np.concatenate((fish, new_fish))

minus = list()
for row in fish:
    
    minus.append([1,0])
    
minus = np.array(minus)

In [58]:
minus

array([[1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0],
       [1, 0]])

In [59]:
fish

array([[1, 8],
       [2, 3],
       [3, 4],
       [4, 4],
       [5, 5],
       [6, 0],
       [7, 0],
       [8, 0]])

In [46]:
# check for zeros
fish[list(zip(*np.where(fish == 0)))[0]] = 7

In [43]:
new_fish

array([[6, 0],
       [7, 0],
       [8, 0]])

In [52]:
fish

array([[1, 8],
       [2, 3],
       [3, 4],
       [4, 4],
       [5, 5]])

In [53]:
new_fish

array([[6, 0],
       [7, 0],
       [8, 0]])